baseURL = 'https://napkinstack.com/'
languageCode = 'en-us'
title = 'napkinstack'
theme = "hugo-theme-terminal"
publishDir = "/home/damon/docker-services/napkinstackhugo/data/nginx/www/html/"

[params]
    contentTypeName = ""

    # ["orange", "blue", "red", "green", "pink"]
    themeColor = "pink"
    
    # if your resource directory contains an image called `cover.(jpg|png|webp)`,
    # then the file will be used as a cover automatically.
    # With this option you don't have to put the `cover` param in a front-matter.
    autoCover = true

    # set post to show the last updated
    # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
    showLastUpdated = true

    enableGitInfo = true

    centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "napkinstack"
    subtitle = "a page for my notes"
    owner = "damon aka napkins"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "napkinstack"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "ict211"
        name = "ict211"
        url = "/ict211"
      [[languages.en.menu.main]]
        identifier = "ict212"
        name = "ict212"
        url = "/ict212"
      [[languages.en.menu.main]]
        identifier = "ict217"
        name = "ict217"
        url = "/ict217"
      [[languages.en.menu.main]]
        identifier = "ict218"
        name = "ict218"
        url = "/ict218"
      [[languages.en.menu.main]]
        identifier = "ict219"
        name = "ict219"
        url = "/ict219"
      [[languages.en.menu.main]]
        identifier = "notes"
        name = "notes"
        url = "/notes"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "home"
        name = "home"
        url = "/"
        weight = -99